CREATE TABLE meals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL
        CHECK (category IN ('breakfast', 'lunch', 'dinner', 'snack')),

    FOREIGN KEY (user_id) REFERENCES users(id)
);