CREATE TABLE goals (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    calories DOUBLE PRECISION NOT NULL,
    protein DOUBLE PRECISION NOT NULL,
    fat DOUBLE PRECISION NOT NULL,
    carbs DOUBLE PRECISION NOT NULL
);